name: 'Tweet Action'

on:
  issues:
    types: labeled

permissions:
  contents: read
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v3
        with:
          github-token: ${{ github.token }}
          config-path: '.github/label-actions.yaml'
          process-only: 'issues'
